name: Train Wine Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  train:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --no-cache-dir -r scripts/requirements.txt
        python -m pip install --no-cache-dir "pyOpenSSL<25" "cryptography<43"

    - name: Run pipeline
      run: python scripts/create_pipeline.py
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
